---
# yaml-language-server: $schema=https://kubernetes-schemas-cvg.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: chaski
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: chaski-secret
    template:
      data:
        RADARR_PUSHOVER_URL: pover://{{ .PUSHOVER_USER_KEY }}@{{ .RADARR_PUSHOVER_TOKEN }}
        SEERR_PUSHOVER_URL: pover://{{ .PUSHOVER_USER_KEY }}@{{ .SEERR_PUSHOVER_TOKEN }}
        SONARR_PUSHOVER_URL: pover://{{ .PUSHOVER_USER_KEY }}@{{ .SONARR_PUSHOVER_TOKEN }}
        PLEX_DISCORD_URL: "{{ .DISCORD_PLEX_APPRISE_URL }}"
  dataFrom:
    - extract:
        key: radarr
    - extract:
        key: seerr
    - extract:
        key: sonarr
    - extract:
        key: pushover
    - extract:
        key: plex
